server:
  port: 8083
  max-http-header-size: 1024000 #请求头太大，实质是图片大
spring:
  application:
    name: manager
  datasource:
    #连接管理员
    db1:
      jdbc-url: jdbc:mysql://121.196.109.178:3306/admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: Wenhao1223
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    #连接鲜花信息
    db2:
      jdbc-url: jdbc:mysql://121.196.109.178:3306/graduate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: Wenhao1223
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  type-aliases-package: com.wen.pojo

  #fastdfs
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #  pool:
  # jmx-enabled: false
  thumb-image:
    width: 150
    height: 150
  tracker-list: 121.196.109.178:22122