server:
  port: 8082
spring:
  application:
    name: email
  datasource:
    url: jdbc:mysql://121.196.109.178:3306/graduate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Wenhao1223
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2071250850@qq.com
    password: hzmfbqiqcpofbgji #打开qq邮箱pop
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  rabbitmq:
    username: wenhao
    password: wenhao
    virtual-host: /
    host: 121.196.109.178
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual #
#        retry:   #重试机制
#          enabled: true  #开启
#          max-attempts: 10 #最大重试次数
#          initial-interval: 2000ms #每次间隔
mybatis:
  type-aliases-package: com.sendmail.pojo
  mapper-locations: classpath:mapper/*.xml