server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://121.196.109.178:3306/graduate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Wenhao1223
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/resources/,classpath:/static/
  mvc:
    date-format: yyyy-MM-dd
    favicon:
      enabled: false
  redis:
    sentinel:
      master: myredis
      nodes: 121.196.109.178:26379
    password: WenhaoZ
    timeout: 8000
    lettuce:
      pool:
        max-active: 8
        max-wait: 8000ms
        max-idle: 8
        min-idle: 0
  mail:
    host: smtp.qq.com
    username: 2071250850@qq.com
    password: jhqenaojveqsbbjc
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  rabbitmq:
    username: wenhao
    password: wenhao
    virtual-host: /
    host: 121.196.109.178
    port: 5672
    publisher-confirm-type: correlated #开启确认机制


mybatis:
  type-aliases-package: com.wen.gradua.pojo
  mapper-locations: classpath:mapper/*.xml

  #fastdfs
fdfs:
  so-timeout: 1500
  connect-timeout: 600
    #  pool:
  # jmx-enabled: false
  thumb-image:
    width: 150
    height: 150
  tracker-list: 121.196.109.178:22122
